// backend/jarvisContext.js
module.exports.jarvisContext = {
  name: "Ayush Srivastava",
  education:
    "B.S. in Computer Science at University at Buffalo (Specialization in Software Engineering). Cumulative GPA: 3.7/4.0. Dean's List: Spring 2024, Fall 2024, Fall 2025, Spring 2026. Awards: 4x Hackathon Winner (Stanford, MIT, Carnegie Mellon, UCLA), Honors Scholar, UB Flagship Scholarship. Expected Graduation: Dec 2026. Open to relocate.",
  about:
    "I love to code and I love plants. 4x hackathon winner across Stanford, MIT, Carnegie Mellon, and UCLA. Right now I'm interning at Linde, where I'm automating workflows and digitizing old processes. Outside of code, I grow bonsai — currently working on a honey locust cutting and a Schefflera arboricola — and I whittle when I want to work with my hands instead of a keyboard. I'm also into philosophy, and I'm slowly working on a book. And when I'm not building or growing something, I'm probably watching a movie.",
  skills: [
    "Java",
    "Python",
    "C/C++",
    "C#",
    "JavaScript",
    "TypeScript",
    "OCaml",
    "React",
    ".NET",
    "Node.js",
    "Express",
    "FastAPI",
    "Docker",
    "Git",
    "Postman",
    "CI/CD",
    "GCP",
    "Azure",
    "RunPod",
    "Supabase",
    "MongoDB",
    "PostgreSQL",
    "Three.js / R3F",
    "Bootstrap",
    "RESTful APIs",
    "JWT Auth",
    "Agile/Scrum",
    "Computer Architecture",
    "Security-first Dev",
    "SolidWorks",
    "Render",
    "Vercel",
  ],
  projects: [
    {
      name: "Dots",
      desc: "Built a tool converting floorplans into tactile braille maps with QR-linked voice and text Q&A for blind and low-vision users. Engineered a pipeline integrating Gemini for tactile map generation and Fetch.ai ASI:One for per-map grounded Q&A. Implemented ElevenLabs voice agent with server-minted short-lived tokens and per-map prompt overrides.",
      link: "https://devpost.com/software/dots-y5r21j",
      github: "https://github.com/axxyush/dots",
    },
    {
      name: "Armie",
      desc: "Built a mixed-reality robotic surgical arm in 48 hours for surgery training, reducing reliance on $500-$3K cadaver specimens. Programmed Arduino Uno Q firmware with dual Bluetooth services enabling teleoperation and real-time patient vitals monitoring. Engineered hardware-AR calibration logic to synchronize physical arm movement with AR visualization on Snap Spectacles.",
      link: "https://devpost.com/software/armie",
      github: "https://github.com/axxyush/ARmie-mithack",
    },
    {
      name: "MeetWise",
      desc: "Created meeting intelligence platform eliminating manual notetaking by enabling AI conversational search over past meetings. Developed secure backend integrating Whisper & Pyannote models for transcription with speaker diarization stored in MongoDB. Implemented frontend with OpenAI-powered query interface allowing natural language questions to retrieve meeting information.",
      link: "https://github.com/axxyush/meetwise",
    },
    {
      name: "Pehcharm",
      desc: "Developed full-stack platform enabling 100+ users to create portfolios, earning 4.5/5 rating from 20+ testers. Enhanced portfolio quality with AI feedback & improved UX by providing features like recommendation & profile-views. Integrated GitHub & Jobs web APIs to fetch user's projects & relevant job opportunities, increasing usability of the platform.",
      link: "https://pehcharm.vercel.app/",
    },
    {
      name: "WALL-E Robot",
      desc: "Engineered a creative website-controlled robot, achieving 80% commands execution performance. Increased structural durability and motor efficiency by 30% by designing and 3D printing custom components. Reduced Bluetooth connectivity setup time by 80% (from 5 to 1 minute) through optimized C++ programming.",
      link: "https://wall-e-one.vercel.app",
    },
    {
      name: "Code Guardian",
      desc: "Marvel-themed 3D portfolio with character skins and an in-browser terminal.",
      link: "https://ayushsri.vercel.app",
    },
    {
      name: "CompInfo / IT Asset Tracker",
      desc: "PostgreSQL based asset management system featuring history logging, Excel import/export, and real-time inventory tracking for 2,500+ devices, reducing lookup time by 90%.",
      link: "https://comp-info.vercel.app",
    },
  ],
  work: [
    {
      title: "Software Engineering Intern",
      organization: "Linde Gas & Equipment",
      dates: "May 2026 – Present",
      location: "Buffalo, NY",
      bulletPoints: [
        "Migrated legacy Gas Tracking app to React & .NET, redesigning UI/UX and digitizing & automating core workflows.",
        "Unified 10+ SAP EDI cert-processing repos into a single app, reducing per-client codebases to one for shared feature deploys.",
        "Prototyped OCR pipeline to extract cylinder data from photos to replace manual entry for 200+ cylinders/day.",
        "Automated Accustar & Sentry ticket processing via custom API, eliminating a ~10 min manual step per ticket across 400+ tickets/month.",
      ],
    },
    {
      title: "Technical Student Assistant",
      organization: "CAS Educational Technology, University at Buffalo",
      dates: "Nov 2024 – May 2026",
      location: "Buffalo, NY",
      bulletPoints: [
        "Built CompInfo, a PostgreSQL based asset management system featuring history logging, Excel import/export, and real-time inventory tracking for 2,500+ devices, reducing lookup time by 90%.",
        "Deployed 80+ workstations (imaging, software & hardware setup) supporting faculty/staff onboarding across departments.",
        "Debugged & resolved 250+ tickets, including software crashes and hardware failures.",
      ],
    },
    {
      title: "DREAM Lab Apprentice",
      organization:
        "School of Engineering and Applied Sciences, University at Buffalo",
      dates: "Jan 2025 – Apr 2025",
      location: "Buffalo, NY",
      bulletPoints: [
        "Built 5+ hardware-software projects using Arduino, SolidWorks & 3D printing, meeting all design specifications.",
        "Mentored 40+ peers through coding fundamentals workshops/events, helping them develop mini-projects.",
        "Completed 4-modules creating ESP32 robot project, earning SEAS Maker Badge for final presentation.",
      ],
    },
    {
      title: "Undergraduate Research Assistant",
      organization: "Embedded Sensing and Computing Lab, University at Buffalo",
      dates: "Jul 2024 – Dec 2024",
      location: "Buffalo, NY",
      bulletPoints: [
        "Developed the frontend for Vocal Lens, a tool detecting Specific Language Impairment in children through voice analysis, cutting diagnosis time by 75%",
        "Built and iterated on the UI through multiple rounds of testing and feedback from 20+ users, improving usability scores by 30%",
      ],
    },
    {
      title: "Social Media Intern",
      organization: "Honors College, University at Buffalo",
      dates: "Aug 2024 – May 2025",
      location: "Buffalo, NY",
      bulletPoints: [
        "Developed content strategies that increased engagement by 45% for UB Honors College social media platforms.",
        "Worked collaboratively with a team of 2 to create content and support 20+ Honors events.",
      ],
    },
    {
      title: "Student Leader",
      organization: "Elli, UB Campus Dining and Shops",
      dates: "Jan 2024 – Nov 2024",
      location: "Buffalo, NY",
      bulletPoints: [
        "Trained 30+ new employees and managed daily operations to ensure smooth service delivery.",
        "Handled high-pressure situations, resolving conflicts and ensuring excellent service for 200+ customers daily while maintaining a welcoming and policy-compliant environment.",
        "Oversaw a diverse team of 5-7 members, ensuring adherence to policies and efficient teamwork.",
      ],
    },
  ],
  contact: {
    email: "ayushsri@buffalo.edu",
    linkedin: "https://www.linkedin.com/in/ayush-sri/",
    github: "https://github.com/axxyush",
    portfolio: "https://ayushsri.vercel.app/",
    phone: "+1 (716) 730-9248",
    location: "Buffalo, NY | Open to Relocate",
  },
  hobbies:
    "Movies, Coding, Web Development, Music, Cooking, Biking, Playing COD",
};
